### ISSUE TITLE
Roadmap to Propel 2

### ISSUE THREAD

**Issue by robin850** [propelorm/propelorm.github.com#240]
Hello world!

I open this issue to put the roadmap to make the site efficient for Propel 2. I'm currently resolving each task (except the upgrade guide since Cristiano is on it).
- [x] **Fix the buidltime guide** : The user won't be able to create the SQL structure following the different steps in the given order since the database credentials aren't yet provided.
- [x] **Bring back the Silex documentation** : Commit https://github.com/propelorm/Propel2/commit/1d891f0cb7ba2ff79ebb12d0a5a77e28d746bd71 didn't ship with the Silex documentation and it hasn't been pulled in the repository
- [ ] **Update all commands' output** : Note a vital issue, we can deploy without this change since it's only in few chapters.
- [x] **Write a guide to upgrade from Propel 1.x to 2.0** : Write a guide widely based on the `UPDATE.md` file and with the new stuff (e.g. new folder's structure).
- [ ] **Check the whole documentation for deprecated mentions/code/features/anything**.
